services:
  - type: web
    name: dash-gncv
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y gdal-bin python3-gdal
      pip install -r requirements.txt
    startCommand: gunicorn app:server
